security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        #  remplace users_in_memory par Pompiste
        app_pompiste_provider:
            entity:
                class: App\Entity\Pompiste
                property: email # Le champ qui sert d'identifiant (ton login)

        app_client_provider:
            entity:
                class: App\Entity\Client
                property: email 

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        
        client_firewall:
            pattern: ^/client
            lazy: true
            provider: app_client_provider
            form_login:
                login_path: app_client_login
                check_path: app_client_login
                default_target_path: pageclient # Ta route après succès
                enable_csrf: true
            logout:
                path: app_client_logout
                target: app_client_login

        main:
            lazy: true
            #  On dit au firewall d'utiliser le provider Pompiste
            provider: app_pompiste_provider

            #   active le formulaire de connexion
            form_login:
                login_path: app_login    # Nom de la route de ta page de login
                check_path: app_login    # La route où le formulaire est soumis
                enable_csrf: true        # Protection contre les attaques CSRF
                default_target_path: app_home   # Où rediriger après le succès ici faut que je mette la page du pompiste une fois connecté 

            #  active la déconnexion
            logout:
                path: app_logout
                # where to redirect after logout
                target: app_login #une fois déconnecté on retourne à la page de connexion 
                # target: app_any_route

    access_control:  #pour controller qui à ecces à quoi 
       
        - { path: ^/pompiste, roles: ROLE_USER }